package com.codecool.bank_db.components;

public class Streets {
    static final String[] STREETS = {
            "ul. Świętokrzyska",
            "ul. Jasna",
            "ul. Marszałkowska",
            "ul. Rysia",
            "ul. Szkolna",
            "ul. Jasna",
            "ul. Marszałkowska",
            "Pl. Młynarskiego Emila",
            "ul. Moniuszki Stanisława",
            "ul. Sienkiewicza Henryka",
            "ul. Boduena Gabriela Piotra",
            "ul. Zgoda",
            "ul. Jasna",
            "ul. Moniuszki Stanisława",
            "ul. Sienkiewicza Henryka",
            "ul. Marszałkowska",
            "ul. Marszałkowska",
            "ul. Zgoda",
            "ul. Złota",
            "ul. Chmielna",
            "ul. Szpitalna",
            "ul. Chmielna",
            "ul. Krucza",
            "ul. Widok",
            "ul. Aleje Jerozolimskie",
            "ul. Krucza",
            "ul. Marszałkowska",
            "ul. Widok",
            "ul. Pasaż Śródmiejski",
            "ul. Bracka",
            "ul. Nowy Świat",
            "Pl. Powstańców Warszawy",
            "ul. Szpitalna",
            "ul. Przeskok",
            "ul. Górskiego Wojciecha",
            "ul. Warecka",
            "ul. Tuwima Juliana",
            "ul. Baczyńskiego Krzysztofa Kamila",
            "ul. Kubusia Puchatka",
            "ul. Moniuszki Stanisława",
            "Pl. Powstańców Warszawy",
            "ul. Warecka",
            "ul. Jasna",
            "ul. Nowy Świat",
            "ul. Czackiego Tadeusza",
            "ul. Świętokrzyska",
            "ul. Nowy Świat",
            "ul. Krakowskie Przedmieście",
            "ul. Mazowiecka",
            "ul. Świętokrzyska",
            "ul. Świętokrzyska",
            "ul. Dowcip",
            "ul. Mazowiecka",
            "ul. Świętokrzyska",
            "ul. Jasna",
            "Pl. Dąbrowskiego Jana Henryka",
            "ul. Kredytowa",
            "Pl. Dąbrowskiego Jana Henryka",
            "ul. Jasna",
            "ul. Rysia",
            "ul. Królewska",
            "ul. Marszałkowska",
            "ul. Kredytowa",
            "ul. Księdza Biskupa Burschego Juliusza",
            "Pl. Małachowskiego Stanisława",
            "ul. Królewska",
            "ul. Królewska",
            "Pl. Małachowskiego Stanisława",
            "ul. Pasaż Niżyńskiego",
            "ul. Traugutta Romualda",
            "ul. Generała Tokarzewskiego Karaszewicza Michała",
            "ul. Krakowskie Przedmieście",
            "ul. Kozia",
            "ul. Krakowskie Przedmieście",
            "ul. Ossolińskich",
            "Pl. Marszałka Piłsudskiego Józefa",
            "ul. Trębacka",
            "ul. Senatorska",
            "ul. Moliera Jana Baptysty",
            "Pl. Teatralny",
            "Pl. Marszałka Piłsudskiego Józefa",
            "ul. Krakowskie Przedmieście",
            "ul. Miodowa",
            "ul. Senatorska",
            "ul. Nowy Przejazd",
            "ul. Daniłowiczowska",
            "ul. Bielańska",
            "ul. Bielańska",
            "ul. Corazziego Antoniego",
            "ul. Tłomackie",
            "ul. Gamerskiego Tylmana",
            "Al. Solidarności",
            "Pl. Bankowy",
            "ul. Hipoteczna",
            "ul. Daniłowiczowska",
            "ul. Wierzbowa",
            "Pl. Bankowy",
            "ul. Senatorska",
            "ul. Fredry Aleksandra",
            "ul. Niecała",
            "ul. Canaletta",
            "ul. Senatorska",
            "ul. Przechodnia",
            "ul. Marszałkowska",
            "ul. Królewska",
            "Pl. Grzybowski",
            "ul. Twarda",
            "ul. Próżna",
            "ul. Zielna",
            "Pl. Grzybowski",
            "Pl. Defilad",
            "ul. Marszałkowska",
            "ul. Bagno",
            "ul. Plater Emilii",
            "ul. Twarda",
            "Pl. Grzybowski",
            "Al. Jana Pawła II",
            "ul. Świętokrzyska",
            "Al. Jana Pawła II",
            "ul. Chmielna",
            "ul. Plater Emilii",
            "ul. Sosnowa",
            "ul. Złota",
            "ul. Sienna",
            "ul. Mariańska",
            "Al. Jana Pawła II",
            "ul. Pańska",
            "ul. Rondo ONZ",
            "ul. Plater Emilii",
            "ul. Sienna",
            "ul. Śliska",
            "ul. Graniczna",
            "ul. Grzybowska",
            "ul. Grzybowska",
            "Al. Jana Pawła II",
            "Al. Jana Pawła II",
            "Pl. Żelaznej Bramy",
            "ul. Elektoralna",
            "Pl. Mirowski",
            "ul. Ptasia",
            "ul. Zimna",
            "Pl. Bankowy",
            "ul. Elektoralna",
            "Al. Solidarności",
            "Al. Jana Pawła II",
            "Pl. Bankowy",
            "ul. Orla",
            "Al. Solidarności",
            "Al. Jana Pawła II",
            "Al. Solidarności",
            "ul. Nowolipie",
            "Al. Generała Andersa Władysława",
            "Al. Jana Pawła II",
            "ul. Karmelicka",
            "ul. Nowolipie",
            "ul. Nowolipki",
            "Al. Jana Pawła II",
            "ul. Nowolipki",
            "ul. Zamenhofa Ludwika",
            "ul. Dzielna",
            "ul. Karmelicka",
            "Al. Jana Pawła II",
            "ul. Anielewicza Mordechaja",
            "ul. Nalewki",
            "Al. Generała Andersa Władysława",
            "ul. Dawidowskiego Alka",
            "ul. Nowolipki",
            "ul. Zamenhofa Ludwika",
            "ul. Anielewicza Mordechaja",
            "ul. Dzielna",
            "ul. Karmelicka",
            "ul. Pawia",
            "ul. Zamenhofa Ludwika",
            "Al. Jana Pawła II",
            "ul. Anielewicza Mordechaja",
            "ul. Karmelicka",
            "ul. Lewartowskiego Józefa",
            "Al. Jana Pawła II",
            "ul. Błońska",
            "ul. Dzika",
            "ul. Karmelicka",
            "ul. Miła",
            "Al. Jana Pawła II",
            "ul. Niska",
            "ul. Skwer Wieźniów Politycznych Stalinizmu",
            "ul. Stawki",
            "ul. Niska",
            "ul. Miła",
            "ul. Karmelicka",
            "ul. Dubois Stanisława",
            "ul. Stawki",
            "ul. Dubois Stanisława",
            "ul. Lewartowskiego Józefa",
            "ul. Karmelicka",
            "ul. Nalewki",
            "ul. Zamenhofa Ludwika",
            "ul. Dubois Stanisława",
            "ul. Inflancka",
            "ul. Lewartowskiego Józefa",
            "ul. Muranowska",
            "ul. Stawki",
            "ul. Dzika",
            "ul. Słomińskiego Zygmunta",
            "ul. Dubois Stanisława",
            "ul. Kłopot",
            "ul. Pokorna",
            "ul. Franciszkańska",
            "Al. Generała Andersa Władysława",
            "ul. Wałowa",
            "ul. Świętojerska",
            "ul. Bonifraterska",
            "ul. Słomińskiego Zygmunta",
            "ul. Franciszkańska",
            "ul. Konwiktorska",
            "Pl. Krasińskich",
            "ul. Międzyparkowa",
            "ul. Muranowska",
            "Al. Generała Andersa Władysława",
            "ul. Wałowa",
            "ul. Bonifraterska",
            "ul. Franciszkańska",
            "ul. Dolańskiego Włodzimierza",
            "ul. Fondamińskiego Edwarda",
            "ul. Sapieżyńska",
            "ul. Konwiktorska",
            "ul. Konwiktorska",
            "ul. Kościelna",
            "ul. Przyrynek",
            "ul. Rajców",
            "ul. Samborska",
            "ul. Burmistrzowska",
            "ul. Rybaki",
            "ul. Sanguszki Romana",
            "ul. Wenedów",
            "ul. Skwer Batalionu AK Gozdawa",
            "ul. Wójtowska",
            "ul. Szymanowska",
            "ul. Zakroczymska",
            "ul. Franciszkańska",
            "ul. Freta",
            "ul. Koźla",
            "ul. Rynek Nowego Miasta",
            "ul. Piesza",
            "ul. Mostowa",
            "ul. Stara",
            "ul. Ciasna",
            "ul. Gomulickiego Wiktora",
            "ul. Franciszkańska",
            "ul. Koźla",
            "ul. Nowiniarska",
            "ul. Świętojerska",
            "ul. Barokowa",
            "ul. Długa",
            "Al. Solidarności",
            "ul. Długa",
            "ul. Bohaterów Getta",
            "Al. Generała Andersa Władysława",
            "ul. Hipoteczna",
            "ul. Kapucyńska",
            "ul. Miodowa",
            "ul. Schillera Leona",
            "ul. Kapitulna",
            "ul. Miodowa",
            "ul. Podwale",
            "ul. Kapitulna",
            "ul. Rycerska",
            "ul. Szeroki Dunaj",
            "ul. Wąski Dunaj",
            "ul. Kilińskiego Jana",
            "ul. Brzozowa",
            "ul. Boleść",
            "ul. Mostowa",
            "ul. Nowomiejska",
            "ul. Podwale",
            "ul. Celna",
            "ul. Długa",
            "ul. Piekarska",
            "ul. Piwna",
            "ul. Świętojańska",
            "Pl. Zamkowy",
            "ul. Wąski Dunaj",
            "ul. Krzywe Koło",
            "ul. Nowomiejska",
            "ul. Rynek Starego Miasta",
            "ul. Zapiecek",
            "ul. Kamienne Schodki",
            "Pl. Zamkowy",
            "ul. Kanonia",
            "ul. Dziekania",
            "ul. Skwer I Dywizji Pancernej",
            "ul. Wybrzeże Gdańskie",
            "ul. Jezuicka",
            "ul. Dawna",
            "ul. Steinkellera Piotra Antoniego",
            "ul. Wodna",
            "ul. Bugaj",
            "ul. Brzozowa",
            "ul. Celna",
            "ul. Świętojańska",
            "ul. Nowy Zjazd",
            "ul. Mariensztat",
            "ul. Boczna",
            "ul. Białoskórnicza",
            "ul. Dobra",
            "ul. Garbarska",
            "ul. Krzywopoboczna",
            "ul. Grodzka",
            "ul. Źródłowa",
            "ul. Bednarska",
            "ul. Browarna",
            "ul. Dobra",
            "ul. Furmańska",
            "ul. Gęsta",
            "ul. Karowa",
            "ul. Lipowa",
            "ul. Wiślana",
            "ul. Sowia",
            "ul. Bednarska",
            "ul. Krakowskie Przedmieście",
            "ul. Karowa",
            "ul. Krakowskie Przedmieście",
            "Pl. Osterwy Juliusza",
            "ul. Karasia Kazimierza",
            "ul. Kopernika Mikołaja",
            "ul. Nowy Świat",
            "ul. Sewerynów",
            "ul. Oboźna",
            "ul. Krakowskie Przedmieście",
            "Al. Na Skarpie",
            "ul. Konopczyńskiego Emiliana",
            "ul. Kopernika Mikołaja",
            "ul. Bartoszewicza Juliana",
            "ul. Browarna",
            "ul. Leszczyńska",
            "ul. Oboźna",
            "ul. Radna",
            "ul. Topiel",
            "ul. Dobra",
            "ul. Drewniana",
            "ul. Elektryczna",
            "ul. Wybrzeże Kościuszkowskie",
            "ul. Smulikowskiego Juliana",
            "ul. Tamka",
            "ul. Topiel",
            "ul. Zajęcza",
            "ul. Cicha",
            "ul. Dynasy",
            "ul. Tamka",
            "ul. Zajęcza",
            "ul. Nowy Świat",
            "ul. Ordynacka",
            "ul. Kopernika Mikołaja",
            "ul. Świętokrzyska",
            "ul. Gałczyńskiego Konstantego Ildefonsa",
            "ul. Przybosia Juliana",
            "ul. Nowy Świat",
            "ul. Ordynacka",
            "ul. Foksal",
            "ul. Kopernika Mikołaja",
            "ul. Okólnik",
            "ul. Ordynacka",
            "ul. Krywulta Aleksandra",
            "ul. Szczygla",
            "ul. Foksal",
            "ul. Nowy Świat",
            "ul. Rondo Generała De Gaulle`a Charlesa",
            "ul. Aleje Jerozolimskie",
            "ul. Smolna",
            "ul. Czerwonego Krzyża",
            "ul. Jaracza Stefana",
            "ul. Wybrzeże Kościuszkowskie",
            "ul. Kruczkowskiego Leona",
            "Al. 3 Maja",
            "ul. Solec",
            "ul. Dobra",
            "ul. Tamka",
            "ul. Kruczkowskiego Leona",
            "ul. Dobra",
            "ul. Smulikowskiego Juliana",
            "ul. Wybrzeże Kościuszkowskie",
            "Al. 3 Maja",
            "ul. Świętego Salezego Franciszka",
            "ul. Potockiego Ignacego",
            "ul. Solec",
            "Al. 3 Maja",
            "ul. Solec",
            "ul. Solec",
            "ul. Ludna",
            "ul. Ludna",
            "ul. Okrąg",
            "ul. Przystaniowa",
            "ul. Solec",
            "ul. Solec",
            "ul. Wioślarska",
            "ul. Kruczkowskiego Leona",
            "ul. Ludna",
            "ul. Ludna",
            "ul. Orłowicza Mieczysława",
            "ul. Okrąg",
            "ul. Czerniakowska",
            "ul. Czerniakowska",
            "ul. Książęca",
            "ul. Rozbrat",
            "ul. Szara",
            "ul. Czerniakowska",
            "ul. Al. Zgrupowania AK Kryska",
            "ul. Wilanowska",
            "ul. Okrąg",
            "ul. Solec",
            "ul. Solec",
            "ul. Dmochowskiego Franciszka Ksawerego",
            "ul. Miechowska",
            "ul. Rozbrat",
            "ul. Śniegockiej Cecylii",
            "ul. Koźmińska",
            "ul. Górnośląska",
            "ul. Profesorska",
            "ul. Hoene-Wrońskiego Józefa Marii",
            "ul. Koźmińska",
            "ul. Czerniakowska",
            "ul. Solec",
            "ul. Solec",
            "ul. Czerniakowska",
            "ul. Zagórna",
            "ul. Idźkowskiego Adama",
            "ul. Górnośląska",
            "ul. Górnośląska",
            "ul. Fabryczna",
            "ul. Górnośląska",
            "ul. Rozbrat",
            "ul. Koźmińska",
            "ul. Łazienkowska",
            "ul. Przemysłowa",
            "ul. Rozbrat",
            "ul. Koźmińska",
            "ul. Czerniakowska",
            "ul. Czerniakowska",
            "ul. Solec",
            "ul. Solec",
            "ul. Jezierskiego Franciszka Salezego",
            "ul. Górnośląska",
            "ul. Hoene-Wrońskiego Józefa Marii nr 1",
            "ul. Myśliwiecka",
            "Al. Szpitala Ujazdowskiego",
            "ul. Agrykola",
            "ul. Skwer Kisielewskiego Stefana Kisiela",
            "ul. Aleje Ujazdowskie",
            "ul. Kusocińskiego Janusza",
            "ul. Podchorążych",
            "ul. Szwoleżerów",
            "ul. 29 Listopada",
            "ul. Nowosielecka",
            "ul. Suligowskiego Adolfa",
            "ul. Dragonów",
            "ul. Jazdów",
            "ul. Kawalerii",
            "ul. Zaruskiego Mariusza",
            "ul. Piękna",
            "ul. Aleje Ujazdowskie",
            "ul. Wiejska",
            "ul. Wiejska",
            "ul. Matejki Jana",
            "ul. Lennona Johna",
            "ul. Piękna",
            "ul. Frascati",
            "ul. Górnośląska",
            "ul. Maszyńskiego Piotra",
            "ul. Nullo Franciszka",
            "ul. Senacka",
            "Al. Na Skarpie",
            "ul. Wiejska",
            "ul. Wiejska",
            "ul. Konopnickiej Marii",
            "ul. Frascati",
            "ul. Prusa Bolesława",
            "ul. Skwer Batalionu AK Miłosz",
            "ul. Aleje Jerozolimskie",
            "ul. Mysia",
            "ul. Nowy Świat",
            "Al. Lorentza Stanisława",
            "ul. Nowy Świat",
            "ul. Książęca",
            "Pl. Trzech Krzyży",
            "ul. Bracka",
            "ul. Bracka",
            "ul. Żurawia",
            "ul. Wspólna",
            "Pl. Trzech Krzyży",
            "ul. Aleje Jerozolimskie",
            "ul. Krucza",
            "ul. Marszałkowska",
            "ul. Nowogrodzka",
            "ul. Krucza",
            "ul. Nowogrodzka",
            "ul. Marszałkowska",
            "ul. Żurawia",
            "ul. Hoża",
            "ul. Marszałkowska",
            "ul. Parkingowa",
            "ul. Grabowskiego Antoniego",
            "ul. Wspólna",
            "ul. Hoża",
            "ul. Krucza",
            "ul. Wspólna",
            "ul. Marszałkowska",
            "ul. Krucza",
            "ul. Krucza",
            "ul. Wspólna",
            "ul. Hoża",
            "ul. Wspólna",
            "ul. Mokotowska",
            "ul. Wilcza",
            "ul. Mokotowska",
            "ul. Mokotowska",
            "Pl. Trzech Krzyży",
            "ul. Aleje Ujazdowskie",
            "ul. Krucza",
            "ul. Mokotowska",
            "ul. Wilcza",
            "ul. Piękna",
            "ul. Aleje Ujazdowskie",
            "ul. Mokotowska",
            "ul. Mokotowska",
            "ul. Mokotowska",
            "ul. Wilcza",
            "ul. Marszałkowska",
            "ul. Księdza Skorupki Ignacego",
            "ul. Piękna",
            "ul. Krucza",
            "ul. Wilcza",
            "ul. Piękna",
            "Pl. Konstytucji",
            "ul. Mokotowska",
            "Pl. Konstytucji",
            "ul. Koszykowa",
            "ul. Marszałkowska",
            "ul. Koszykowa",
            "Al. Róż",
            "ul. Aleje Ujazdowskie",
            "ul. Mokotowska",
            "ul. Calinescu Armanda",
            "ul. Chopina Fryderyka",
            "ul. Sieroszewskiego Wacława",
            "ul. Mokotowska",
            "ul. Mokotowska",
            "ul. Koszykowa",
            "ul. Natolińska",
            "ul. Marszałkowska",
            "ul. Koszykowa",
            "Al. Przyjaciół",
            "ul. Teresy",
            "ul. Aleje Ujazdowskie",
            "ul. Natolińska",
            "ul. Służewska",
            "Al. Wyzwolenia",
            "Pl. Zbawiciela",
            "Al. Armii Ludowej",
            "Al. Wyzwolenia",
            "Pl. Zbawiciela",
            "ul. Czerwijowskiego Faustyna",
            "ul. Sempołowskiej Stefanii",
            "Al. Armii Ludowej",
            "ul. Litewska",
            "ul. Marszałkowska",
            "ul. Sempołowskiej Stefanii",
            "Al. Szucha Jana Chrystiana",
            "ul. Litewska",
            "ul. Marszałkowska",
            "Al. Szucha Jana Chrystiana",
            "ul. Aleje Ujazdowskie",
            "Pl. Na Rozdrożu",
            "ul. Bagatela",
            "ul. Flory",
            "Pl. Unii Lubelskiej",
            "ul. Litewska",
            "ul. Marszałkowska",
            "ul. Bacciarellego Marcelego",
            "ul. Klonowa",
            "ul. Spacerowa",
            "ul. Belwederska",
            "Al. Armii Ludowej",
            "Al. Niepodległości",
            "Al. Armii Ludowej",
            "ul. Lekarska",
            "ul. Filtrowa",
            "ul. Chałubińskiego Tytusa",
            "ul. Rektorska",
            "ul. Rychlińskiego Stanisława",
            "ul. Boya-Żeleńskiego Tadeusza",
            "ul. Polna",
            "Pl. Unii Lubelskiej",
            "ul. Marszałkowska",
            "ul. Polna",
            "ul. Marszałkowska",
            "ul. Zoli Emila",
            "ul. Marszałkowska",
            "ul. Oleandrów",
            "ul. Polna",
            "ul. Waryńskiego Ludwika",
            "Al. Armii Ludowej",
            "ul. Polna",
            "ul. Jaworzyńska",
            "ul. Podoskich Romana i Jana",
            "ul. Polna",
            "ul. Rondo Jazdy Polskiej",
            "ul. Waryńskiego Ludwika",
            "Al. Armii Ludowej",
            "Al. Armii Ludowej",
            "ul. Marszałkowska",
            "ul. Mokotowska",
            "ul. Mokotowska",
            "Pl. Zbawiciela",
            "ul. Nowowiejska",
            "ul. Polna",
            "ul. Waryńskiego Ludwika",
            "Pl. Konstytucji",
            "ul. Marszałkowska",
            "ul. Nowowiejska",
            "ul. Waryńskiego Ludwika",
            "Pl. Zbawiciela",
            "ul. Nowowiejska",
            "ul. Śniadeckich",
            "ul. Waryńskiego Ludwika",
            "ul. Śniadeckich",
            "Pl. Konstytucji",
            "ul. Lwowska",
            "ul. Koszykowa",
            "ul. Koszykowa",
            "ul. Lwowska",
            "Pl. Politechniki",
            "ul. Koszykowa",
            "Al. Niepodległości",
            "ul. Noakowskiego Stanisława",
            "ul. Profesora Wierzbickiego Witolda",
            "ul. Nowowiejska",
            "ul. Noakowskiego Stanisława",
            "ul. Koszykowa",
            "ul. Noakowskiego Stanisława",
            "ul. Skwer 3 Batalionu Pancernego AK Golski",
            "ul. Plater Emilii",
            "ul. Wilcza",
            "ul. Koszykowa",
            "ul. Piękna",
            "ul. Koszykowa",
            "Pl. Konstytucji",
            "ul. Koszykowa",
            "ul. Marszałkowska",
            "ul. Piękna",
            "ul. Wilcza",
            "ul. Wilcza",
            "ul. Żurawia",
            "ul. Poznańska",
            "ul. Hoża",
            "ul. Hoża",
            "ul. Marszałkowska",
            "ul. Wspólna",
            "ul. Poznańska",
            "ul. Świętej Barbary",
            "ul. Wspólna",
            "ul. Plater Emilii",
            "ul. Poznańska",
            "ul. Nowogrodzka",
            "ul. Aleje Jerozolimskie",
            "ul. Marszałkowska",
            "ul. Nowogrodzka",
            "ul. Pankiewicza Jana",
            "ul. Aleje Jerozolimskie",
            "ul. Plater Emilii",
            "ul. Nowogrodzka",
            "ul. Czerniakowska",
            "ul. Wolicka",
            "ul. Kątna",
            "ul. Polska",
            "ul. Gościniec",
            "ul. Gwintowa",
            "ul. Bananowa",
            "ul. Nadrzeczna",
            "ul. Łososiowa",
            "ul. Koszykarska",
            "ul. Żenczykowskiego Wacława",
            "ul. Dyżewskiego Aleksandra",
            "ul. Hempla Stanisława",
            "ul. Ku Wiśle",
            "ul. Ponikowskiego Antoniego",
            "ul. Pszenickiego Andrzeja",
            "ul. Wasiutyńskiego Zbigniewa",
            "ul. Rodzynkowa",
            "ul. Siekierkowska",
            "ul. Bartoszka Franciszka",
            "ul. Idzikowskiego Ludwika",
            "ul. Kozłowskiej Heleny",
            "ul. Piekałkiewicza Jana",
            "ul. Witosa Wincentego",
            "ul. Ananasowa",
            "ul. Gąsocińska",
            "Al. Polski Walczącej",
            "ul. Batalionu AK Karpaty",
            "ul. Bluszczańska",
            "ul. Dywizjonu AK Jeleń",
            "ul. Melomanów",
            "ul. Wojskowej Służby Kobiet",
            "ul. Al. Godziny W",
            "ul. Batalionu AK Bałtyk",
            "ul. Batalionu AK Olza",
            "ul. Batalionu AK Ryś",
            "ul. Cytrynowa",
            "ul. Daktylowa",
            "ul. Figowa",
            "ul. Grupy AK Północ",
            "ul. Niewielka",
            "ul. Pod Kopcem",
            "ul. Pułku AK Broda",
            "ul. Pułku AK Kampinos",
            "ul. Pułku AK Waligóra",
            "ul. Czerniakowska",
            "ul. Czerniakowska",
            "ul. Bartycka",
            "ul. Czerniakowska",
            "ul. Czerniakowska",
            "ul. Nehru Jawaharlala",
            "ul. Zwierzyniecka",
            "ul. Czerniakowska",
            "ul. Podchorążych",
            "ul. Podchorążych",
            "ul. Chełmska",
            "ul. Chełmska",
            "ul. Cybulskiego Zbyszka",
            "ul. Polkowska",
            "ul. Teresińska",
            "ul. Bobrowiecka",
            "ul. Kierbedzia Stanisława",
            "ul. Huculska",
            "ul. Jazgarzewska",
            "ul. Jedwabnicza",
            "ul. Czerska",
            "ul. Łużycka",
            "ul. Kaszubska",
            "ul. Lubkowska",
            "ul. Krasnołęcka",
            "ul. Iwicka",
            "ul. Banioska",
            "ul. Zakrzewska",
            "ul. Sielecka",
            "ul. Stępińska",
            "ul. Górska",
            "ul. Nowotarska",
            "ul. Tatrzańska",
            "ul. Nabielaka Ludwika",
            "ul. Stopowa",
            "ul. Turecka",
            "ul. Zbierska",
            "ul. Sułkowicka",
            "ul. Gagarina Jurija",
            "ul. Gagarina Jurija",
            "ul. Hołówki Tadeusza",
            "ul. Nowosielecka",
            "ul. Badowska",
            "ul. Gagarina Jurija",
            "ul. Gagarina Jurija",
            "ul. Sulkiewicza Aleksandra",
            "ul. Kręta",
            "ul. Lądowa",
            "ul. Parkowa",
            "ul. Belwederska",
            "ul. Belwederska",
            "ul. Sobieskiego Jana",
            "ul. Sobieskiego Jana",
            "ul. Sobieszynska",
            "ul. Piaseczyńska",
            "ul. Jaworowska",
            "ul. Bandoski",
            "ul. Kostrzewskiego Franciszka",
            "ul. Beethovena Ludwika",
            "ul. Hańczy Władysława",
            "ul. Węgrzyna Józefa",
            "ul. Piwarskiego Jana Feliksa",
            "ul. Braci Pillatich",
            "ul. Gierymskiego Aleksandra",
            "ul. Dolna",
            "ul. Dolna",
            "ul. Konduktorska",
            "ul. Padewska",
            "ul. Pytlasińskiego",
            "ul. Włoska",
            "ul. Promenada",
            "ul. Ludowa",
            "ul. Boryszewska",
            "ul. Wygoda",
            "ul. Smetany Bedrzycha",
            "ul. Dworkowa",
            "ul. Grottgera Artura",
            "ul. Pogodna",
            "ul. Zajączkowska",
            "ul. Spacerowa",
            "ul. Wybieg",
            "ul. Humańska",
            "ul. Słoneczna",
            "ul. Willowa",
            "ul. Chocimska",
            "ul. Olszewska",
            "ul. Kujawska",
            "ul. Goworka",
            "ul. Skolimowska",
            "ul. Chmielna",
            "ul. Żelazna",
            "ul. Aleje Jerozolimskie",
            "Al. Jana Pawła II",
            "ul. Chmielna",
            "ul. Żelazna",
            "ul. Aleje Jerozolimskie",
            "ul. Platynowa",
            "ul. Miedziana",
            "ul. Srebrna",
            "ul. Towarowa",
            "ul. Wronia",
            "ul. Aleje Jerozolimskie",
            "ul. Miedziana",
            "ul. Sienna",
            "ul. Żelazna",
            "ul. Twarda",
            "ul. Złota",
            "ul. Sienna",
            "ul. Złota",
            "ul. Twarda",
            "Al. Jana Pawła II",
            "ul. Twarda",
            "ul. Sienna",
            "ul. Śliska",
            "ul. Pańska",
            "Al. Jana Pawła II",
            "ul. Pańska",
            "ul. Twarda",
            "ul. Żelazna",
            "ul. Sienna",
            "ul. Pańska",
            "ul. Miedziana",
            "ul. Żelazna",
            "ul. Pańska",
            "ul. Prosta",
            "ul. Towarowa",
            "ul. Wronia",
            "ul. Żelazna",
            "ul. Łucka",
            "ul. Grzybowska",
            "ul. Łucka",
            "ul. Wronia",
            "ul. Towarowa",
            "ul. Żelazna",
            "ul. Pereca Icchaka Lejba",
            "ul. Prosta",
            "ul. Waliców",
            "ul. Żelazna",
            "ul. Twarda",
            "Al. Jana Pawła II",
            "ul. Ciepła",
            "ul. Grzybowska",
            "ul. Ciepła",
            "ul. Grzybowska",
            "ul. Krochmalna",
            "ul. Waliców",
            "ul. Żelazna",
            "Al. Jana Pawła II",
            "ul. Chłodna",
            "ul. Kotlarska",
            "ul. Towarowa",
            "ul. Wronia",
            "ul. Żelazna",
            "ul. Chłodna",
            "ul. Ogrodowa",
            "ul. Wronia",
            "ul. Żelazna",
            "ul. Ogrodowa",
            "Al. Solidarności",
            "ul. Wronia",
            "ul. Żelazna",
            "ul. Chłodna",
            "ul. Elektoralna",
            "ul. Ogrodowa",
            "ul. Żelazna",
            "ul. Biała",
            "ul. Dobrzańskiego Bronisława",
            "ul. Ogrodowa",
            "Al. Solidarności",
            "Al. Solidarności",
            "Al. Jana Pawła II",
            "ul. Admiralska",
            "ul. Czerwonych Beretów",
            "ul. Frontowa",
            "ul. Gierczak Emilii",
            "ul. Okurzałego Michała",
            "ul. Pontonierów",
            "ul. Topograficzna",
            "Al. Jana Pawła II",
            "ul. Nowolipie",
            "Al. Solidarności",
            "ul. Żelazna",
            "ul. Nowolipie",
            "ul. Nowolipki",
            "Al. Jana Pawła II",
            "ul. Smocza",
            "ul. Nowolipki",
            "ul. Nowolipie",
            "ul. Smocza",
            "ul. Kacza",
            "ul. Żytnia",
            "ul. Skwer Księdza Kardynała Wyszyńskiego Stefana",
            "ul. Wronia",
            "Al. Solidarności",
            "ul. Żelazna",
            "ul. Wolność",
            "ul. Nowolipki",
            "ul. Smocza",
            "Al. Jana Pawła II",
            "ul. Bellottiego Józefa",
            "ul. Dzielna",
            "ul. Skwer Generała Jura-Gorzechowskiego Jana",
            "Al. Jana Pawła II",
            "ul. Pawia",
            "ul. Anielewicza Mordechaja",
            "ul. Smocza",
            "ul. Dzielna",
            "ul. Pawia",
            "Al. Jana Pawła II",
            "ul. Anielewicza Mordechaja",
            "ul. Miła",
            "ul. Smocza",
            "ul. Niska",
            "ul. Miła",
            "Al. Jana Pawła II",
            "ul. Dzika",
            "ul. Stawki",
            "ul. Smocza",
            "ul. Okopowa",
            "ul. Okopowa",
            "ul. Spokojna",
            "ul. Kolska",
            "ul. Niska",
            "ul. Miła",
            "ul. Smocza",
            "ul. Esperanto",
            "ul. Miła",
            "ul. Smocza",
            "ul. Anielewicza Mordechaja",
            "ul. Smocza",
            "ul. Paszyna Jana",
            "ul. Smocza",
            "ul. Anielewicza Mordechaja",
            "ul. Pawia",
            "ul. Okopowa",
            "ul. Anielewicza Mordechaja",
            "ul. Mireckiego Józefa",
            "ul. Okopowa",
            "ul. Kacza",
            "ul. Młocińska",
            "ul. Burakowska",
            "ul. Piaskowa",
            "ul. Słodowiecka",
            "ul. Boznańskiej Olgi",
            "ul. Człuchowska",
            "ul. Pola Wincentego",
            "ul. Strąkowa",
            "ul. Stroma",
            "ul. Znana",
            "ul. Smolki Stanisława",
            "ul. Jana Olbrachta",
            "ul. Redutowa",
            "ul. Baltazara",
            "ul. Matlakowskiego Władysława",
            "ul. Norwida Cypriana Kamila",
            "ul. Szulborska",
            "ul. Sowińskiego Józefa Longina",
            "ul. Nakielska",
            "ul. Redutowa",
            "ul. Antka Rozpylacza",
            "ul. Pustola",
            "ul. Jana Olbrachta",
            "ul. Sowińskiego Józefa Longina",
            "ul. Górczewska",
            "ul. Górczewska",
            "ul. Jana Olbrachta",
            "ul. Góralska",
            "ul. Krysta Jana",
            "ul. Szczecińskiego",
            "ul. Ulrychowska",
            "ul. Okocimska",
            "ul. Traktorzystki",
            "ul. Małego Franka",
            "ul. Ciołka Erazma",
            "ul. Górczewska",
            "ul. Batalionu Parasol",
            "ul. Bitwy pod Lenino",
            "ul. Elekcyjna",
            "ul. Batalionu Parasol",
            "ul. Monte Cassino",
            "ul. Baonu Zośka",
            "ul. Garbińskiego Kajetana",
            "ul. Elekcyjna",
            "ul. Wolska",
            "ul. Moczydło",
            "ul. Elekcyjna",
            "ul. Pustola",
            "ul. Baonu Zośka",
            "ul. Redutowa",
            "ul. Syreny",
            "ul. Wolska",
            "ul. Płocka",
            "ul. Sokołowska",
            "ul. Wojciecha",
            "ul. Płocka",
            "ul. Górczewska",
            "ul. Rabsztyńska",
            "ul. Syreny",
            "ul. Wolska",
            "ul. Sokołowska",
            "ul. Rabsztyńska",
            "ul. Górczewska",
            "ul. Syreny",
            "ul. Tyszkiewicza Eustachego",
            "ul. Górczewska",
            "ul. Płocka",
            "ul. Żytnia",
            "ul. Syreny",
            "ul. Gostyńska",
            "ul. Płocka",
            "ul. Długosza Jana",
            "ul. Gostyńska",
            "ul. Grenady",
            "ul. Syreny",
            "ul. Żytnia",
            "ul. Tyszkiewicza Eustachego",
            "ul. Agawy",
            "ul. Złocienia",
            "ul. Syreny",
            "ul. Grenady",
            "ul. Płocka",
            "ul. Obozowa",
            "ul. Wawrzyszewska",
            "ul. Świętego Stanisława",
            "ul. Kozielska",
            "ul. Ostroroga Jana",
            "ul. Sołtyka Kajetana",
            "ul. Tatarska",
            "ul. Banderii",
            "ul. Radziwie",
            "ul. Gostyńska",
            "ul. Płocka",
            "ul. Zawiszy",
            "ul. Syreny",
            "ul. Złocienia",
            "ul. Młynarska",
            "ul. Młynarska",
            "ul. Tyszkiewicza Eustachego",
            "ul. Wierzynka Mikołaja",
            "ul. Płocka",
            "ul. Długosza Jana",
            "ul. Leszno",
            "ul. Młynarska",
            "ul. Leonarda",
            "ul. Długosza Jana",
            "ul. Szlenkierów",
            "ul. Żytnia",
            "ul. Górczewska",
            "Pl. Opolski",
            "ul. Szlenkierów",
            "ul. Tyszkiewicza Eustachego",
            "ul. Leonarda",
            "ul. Działdowska",
            "ul. Wawelberga Hipolita",
            "ul. Górczewska",
            "ul. Wolska",
            "ul. Staszica Stanisława",
            "ul. Wawelberga Hipolita",
            "ul. Górczewska",
            "ul. Barona Henryka",
            "ul. Gibalskiego Edwarda",
            "ul. Żytnia",
            "ul. Leszno",
            "ul. Karolkowa",
            "ul. Młynarska",
            "Al. Solidarności",
            "ul. Wolska",
            "ul. Karolkowa",
            "ul. Żytnia",
            "ul. Leszno",
            "ul. Wolska",
            "ul. Jaktorowska",
            "ul. Karolkowa",
            "ul. Siedmiogrodzka",
            "ul. Młynarska",
            "ul. Rogalińska",
            "ul. Karolkowa",
            "ul. Przyokopowa",
            "ul. Hrubieszowska",
            "ul. Kolejowa",
            "ul. Szarych Szeregów",
            "ul. Giełdowa",
            "ul. Kasprzaka Marcina",
            "ul. Szarych Szeregów",
            "ul. Korczaka Janusza",
            "ul. Szymańskiego Edwarda",
            "ul. Laskowa",
            "ul. Zegadłowicza Emila",
            "ul. Brylowska",
            "ul. Skwer Pawełka Alojzego",
            "ul. Kolejowa",
            "ul. Sławińska",
            "ul. Zwrotnicza",
            "ul. Krzyżanowskiego Seweryna",
            "ul. Tunelowa",
            "ul. Prądzyńskiego Ignacego",
            "ul. Czelińska",
            "ul. Kasprzaka Marcina",
            "ul. Bema Józefa",
            "ul. Ludwiki",
            "ul. Szymczaka Jana",
            "ul. Klonowicza Sebastiana",
            "ul. Wolska",
            "ul. Skierniewicka",
            "ul. Płocka",
            "ul. Siedmiogrodzka",
            "ul. Bema Józefa",
            "ul. Kasprzaka Marcina",
            "ul. Wolska",
            "ul. Grabowska",
            "ul. Ordona Juliusza Konstantego",
            "ul. Stańczyka",
            "ul. Prądzyńskiego Ignacego",
            "ul. Władysława Warneńczyka",
            "ul. Wschowska",
            "ul. Wieluńska",
            "ul. Tylna",
            "Al. Prymasa Tysiąclecia",
            "ul. Prądzyńskiego Ignacego",
            "ul. Bema Józefa",
            "ul. Bema Józefa",
            "ul. Armatnia",
            "ul. Gumińska",
            "ul. Jana Kazimierza",
            "ul. Gizów",
            "ul. Goleszowska",
            "ul. Boguszewska",
            "ul. Worcella Stanisława",
            "ul. Sowińskiego Józefa Longina",
            "ul. Przyce",
            "ul. Gniewkowska",
            "ul. Mszczonowska",
            "ul. Grodziska",
            "ul. Fort Wola",
            "ul. Wolska",
            "ul. Studzienna",
            "ul. Budziszyńska",
            "ul. Radzanowska",
            "ul. Karlińskiego Kacpra"
    };
}
